{% set name = "cleanlab" %}
{% set version = "2.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bcec81632596eb1d34885546216dac8f790a833ec3747f77d02fd26d6883f6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.22.0
    - python >=3.8
    - scikit-learn >=1.1
    - termcolor >=2.4.0
    - tqdm >=4.53.0
    - pandas >=1.4.0

test:
  imports:
    - cleanlab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cleanlab/cleanlab
  summary: The standard package for machine learning with noisy labels and finding mislabeled data in Python.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/cleanlab/#description
  dev_url: https://github.com/cleanlab/cleanlab
  description: |
    cleanlab is the data-centric ML ops package for machine learning with noisy labels.
    cleanlab cleans labels and supports finding, quantifying, and learning with
    label errors in datasets. See datasets cleaned with cleanlab at labelerrors.com.

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
    - BastianZim
