{% set name = "cleanlab" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c9ec2e2dc2f46b9aaaa46d8b4f0f2c1c080f15997dc1a6cf517fedbe19773d9

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.4
  run:
    - numpy >=1.11.3
    - python =2.7|>=3.4
    - scikit-learn >=0.18
    - scipy >=1.1.0
    - tqdm >=4.53.0

test:
  imports:
    - cleanlab
    - cleanlab.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cgnorthcutt/cleanlab
  summary: The standard package for machine learning with noisy labels and finding mislabeled data in Python.
  license: AGPL-3.0-only
  license_file: LICENSE
  doc_url: "https://pypi.org/project/cleanlab/#description"
  dev_url: https://github.com/cgnorthcutt/cleanlab
  description: |
    cleanlab is the data-centric ML ops package for machine learning with noisy labels.
    cleanlab cleans labels and supports finding, quantifying, and learning with
    label errors in datasets. See datasets cleaned with cleanlab at labelerrors.com.

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
